---
apiVersion: v1
kind: Service
metadata:
  name: clair
spec:
  ports:
    - port: 6060
      name: port0
    - port: 6061
      name: port1
  selector:
    app: clair
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: clair
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clair
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: clairsecret
      containers:
        - name: clair
          image: quay.io/coreos/clair:v2.1.4
          args:
            - "-config"
            - "/config/config.yml"
          ports:
            - containerPort: 6060
            - containerPort: 6061
          volumeMounts:
            - mountPath: /config
              name: secret-volume
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None
