---
- name: Create secrets from config.yml
  command: "mkdir -p {{manifest_base_dir}}/.ssh > /dev/null"

- name: Generate ssh keys
  command: 'cat /dev/zero | ssh-keygen -q -f "{{manifest_base_dir}}/.ssh" -N "" > /dev/null'

- name: Create secrets from ssh key
  command: "kubectl create secret generic ssh-key --from-file={{manifest_base_dir}}/.ssh"


#begin: for running locally
- name: Enable ingress for minikube
  command: "minikube addons enable ingress"

# STEP: add mapping from hostname in ingress to ingress IP in /etc/hosts file
#end

# STEP: apply k8s manifests