version: '3'
services:
  my-sql-database:
    image: "mysql:5.7.13"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    expose:
      - "3306"
    ports:
    - "3306:3306"
    volumes:
      - ./database/init.sql:/script/init.sql
    command: "--init-file /script/init.sql"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOSTNAME: "my-sql-database"
      CLAIR_HOSTNAME: "clair"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - "my-sql-database"
      - "clair"
    volumes:
        - ~/.ssh/test-cs3219:/root/.ssh
        - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/docker-entrypoint.sh
    restart: on-failure
  clair:
    image: quay.io/coreos/clair:v2.1.4
    command: -config=/config/config.yaml
    ports:
      - "6060:6060"
      - "6061:6061"
    depends_on:
      - clairdb
    volumes:
      - $PWD/deployments/roles/clair/templates/local/config.yaml:/config/config.yaml
    restart: on-failure
  clairdb:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
