version: 2
jobs:
  build:
    environment:
      - IMAGE_REPO: cs3219sm
      - IMAGE_NAME: cve-scanner
      - DOCKER_USER: cs3219sm
    docker:
      - image: cimg/node:14.0.0
        user: root
    working_director: ~/backend-cs3219
    steps:
      - checkout

      - setup_remote_docker:

      - run: node --version

      - restore_cache:
          keys:
            - node_deps-{{ checksum "package.json" }}
            # fallback to using latest cache if no match found
            - node-deps-

      - run:
          name: Install deps
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_deps-{{ checksum "package.json" }}

      - run:
          name: Run tests
#          command: |
#            FAILURES=$(npm run test-dev | grep -i fail)
#            if [[ -z "$FAILURES" ]]; then
#              echo "All tests passed!";
#              exit 0;
#            else
#              echo "Tests failed, not building docker image.";
#              exit 1;
#            fi
          command: npm run test-dev
      - run:
          name: Build docker image
          command: docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:$CIRCLE_SHA1 .

      - run:
          name: Authenticate docker
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Push docker image
          command: docker push ${IMAGE_REPO}/${IMAGE_NAME}:$CIRCLE_SHA1
