---
- name: Generate deployments config files from tmpl
  template:
    src: "config.yml"
    dest: "{{manifest_base_dir}}/config.yml"

- name: Create secrets from config.yml
  command: "kubectl create secret generic clairsecret --from-file={{manifest_base_dir}}/config.yml"